import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveEpochMediaRegionId } from "./regionAliases.ts";

export const EPOCH_SCENE_VARIANT_WIDTH = 1280;
export const EPOCH_SCENE_VARIANT_HEIGHT = 720;
export const EPOCH_SCENE_VARIANT_CONTENT_TYPE = "image/png" as const;

const serverRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const defaultPackageRoot = join(serverRoot, "package");

export type EpochSceneVariantKey =
  | "gray_harbor_dawn"
  | "gray_harbor_rain"
  | "gray_harbor_market_evening"
  | "gray_harbor_quiet_midnight"
  | "ash_outpost_sunrise"
  | "ash_outpost_storm"
  | "ash_outpost_noon_watch"
  | "ash_outpost_night_forge"
  | "salt_mirror_noon"
  | "salt_mirror_fog"
  | "salt_mirror_dawn_trade"
  | "salt_mirror_twilight_brine"
  | "glass_archive_morning"
  | "glass_archive_eclipse"
  | "glass_archive_noon_index"
  | "glass_archive_twilight_vigil"
  | "moonwell_hollow_twilight"
  | "moonwell_hollow_night"
  | "moonwell_hollow_dawn_training"
  | "moonwell_hollow_noon_grove"
  | "black_harbor_fog_dawn"
  | "black_harbor_low_tide_night"
  | "forest_green_dawn"
  | "forest_rain_glade"
  | "salt_gate_wind_dawn"
  | "salt_gate_market_noon"
  | "ash_waste_red_dusk"
  | "ash_waste_cold_night"
  | "city_pipes_sodium_dawn"
  | "city_pipes_overflow_night"
  | "abandoned_mine_dust_noon"
  | "abandoned_mine_blue_night"
  | "data_tower_static_dawn"
  | "data_tower_cache_rain"
  | "orbit_city_sunrise_dock"
  | "orbit_city_eclipse_watch"
  | "trench_blue_midnight"
  | "trench_pressure_fog"
  | "collective_dream_pool_twilight"
  | "collective_dream_pool_eclipse"
  | "space_rift_violet_dawn"
  | "space_rift_starfall_night"
  | "non_euclidean_cave_bent_noon"
  | "non_euclidean_cave_eclipse_fold"
  | "starship_graveyard_cold_dawn"
  | "starship_graveyard_eclipse_drift"
  | "abandoned_subway_mist_morning"
  | "abandoned_subway_moonlit_tunnel"
  | "holographic_theater_neon_dusk"
  | "holographic_theater_rain_rehearsal"
  | "quantum_laboratory_probability_morning"
  | "quantum_laboratory_eclipse_trial"
  | "reflective_city_glare_noon"
  | "reflective_city_neon_rain"
  | "data_alley_static_dawn"
  | "data_alley_blackout_night"
  | "prism_waters_rainbow_dawn"
  | "prism_waters_fog_night"
  | "probability_greenhouse_morning_bloom"
  | "probability_greenhouse_eclipse_harvest"
  | "prophecy_server_dawn_query"
  | "prophecy_server_eclipse_verdict"
  | "orbital_cathedral_sunrise_bells"
  | "orbital_cathedral_moonlit_procession";

export type EpochSceneVariantTimeOfDay = "dawn" | "morning" | "noon" | "dusk" | "twilight" | "night";
export type EpochSceneVariantWeather = "mist" | "rain" | "ashfall" | "emberstorm" | "clear" | "brine_fog" | "eclipse" | "silver_dust" | "moonlit";

export interface EpochSceneVariantRecord {
  readonly variantKey: EpochSceneVariantKey;
  readonly regionId: string;
  readonly title: string;
  readonly subtitle: string;
  readonly fileName: string;
  readonly path: string;
  readonly url: string;
  readonly contentType: typeof EPOCH_SCENE_VARIANT_CONTENT_TYPE;
  readonly width: number;
  readonly height: number;
  readonly palette: readonly string[];
  readonly accentColor: string;
  readonly publicAlt: string;
  readonly timeOfDay: EpochSceneVariantTimeOfDay;
  readonly weather: EpochSceneVariantWeather;
  readonly motif: "harbor" | "outpost" | "coast" | "archive" | "moonwell" | "blackharbor" | "forest" | "saltgate" | "ashwaste" | "citypipes" | "mine" | "data-tower" | "orbit-city" | "trench" | "dream-pool" | "space-rift" | "non-euclidean" | "starship-graveyard" | "abandoned-subway" | "holographic-theater" | "quantum-laboratory" | "reflective-city" | "data-alley" | "prism-waters" | "probability-greenhouse" | "prophecy-server" | "orbital-cathedral";
}

export interface EpochSceneVariantManifestEntry {
  readonly variantKey: EpochSceneVariantKey;
  readonly regionId: string;
  readonly title: string;
  readonly subtitle: string;
  readonly path: string;
  readonly url: string;
  readonly contentType: typeof EPOCH_SCENE_VARIANT_CONTENT_TYPE;
  readonly width: number;
  readonly height: number;
  readonly timeOfDay: EpochSceneVariantTimeOfDay;
  readonly weather: EpochSceneVariantWeather;
  readonly sha256: string;
}

export interface EpochSceneVariantMedia {
  readonly variantKey: EpochSceneVariantKey;
  readonly regionId: string;
  readonly title: string;
  readonly subtitle: string;
  readonly palette: readonly string[];
  readonly accentColor: string;
  readonly publicAlt: string;
  readonly assetPath: string;
  readonly imageUrl: string;
  readonly contentType: typeof EPOCH_SCENE_VARIANT_CONTENT_TYPE;
  readonly width: number;
  readonly height: number;
  readonly timeOfDay: EpochSceneVariantTimeOfDay;
  readonly weather: EpochSceneVariantWeather;
}

export const EPOCH_SCENE_VARIANTS = [
  {
    variantKey: "gray_harbor_dawn",
    regionId: "region_gray_harbor",
    title: "灰港破晓",
    subtitle: "晨雾、灯塔余光和早班码头登记",
    fileName: "gray-harbor-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/gray-harbor-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/gray-harbor-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#07151d", "#164e63", "#67e8f9", "#f5d08a"],
    accentColor: "#67e8f9",
    publicAlt: "灰港破晓时的晨雾码头、灯塔余光、登记棚和湿冷石阶。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "harbor",
  },
  {
    variantKey: "gray_harbor_rain",
    regionId: "region_gray_harbor",
    title: "灰港雨夜",
    subtitle: "黑雨、潮灯和低声交易的避雨棚",
    fileName: "gray-harbor-rain-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/gray-harbor-rain-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/gray-harbor-rain-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#030910", "#0f3a4a", "#38bdf8", "#94a3b8"],
    accentColor: "#38bdf8",
    publicAlt: "灰港雨夜的潮灯、黑雨斜线、避雨棚和远处巡逻剪影。",
    timeOfDay: "night",
    weather: "rain",
    motif: "harbor",
  },
  {
    variantKey: "gray_harbor_market_evening",
    regionId: "region_gray_harbor",
    title: "灰港灯市薄暮",
    subtitle: "傍晚开市、潮灯点亮和委托牌重新排序",
    fileName: "gray-harbor-market-evening-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/gray-harbor-market-evening-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/gray-harbor-market-evening-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#061015", "#155e75", "#f59e0b", "#fef3c7"],
    accentColor: "#f59e0b",
    publicAlt: "灰港灯市薄暮时的潮线摊棚、点亮的挂灯、委托牌和归港人影。",
    timeOfDay: "dusk",
    weather: "clear",
    motif: "harbor",
  },
  {
    variantKey: "gray_harbor_quiet_midnight",
    regionId: "region_gray_harbor",
    title: "灰港静夜码头",
    subtitle: "午夜低雾、空码头和只剩巡灯的委托墙",
    fileName: "gray-harbor-quiet-midnight-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/gray-harbor-quiet-midnight-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/gray-harbor-quiet-midnight-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#0f172a", "#38bdf8", "#94a3b8"],
    accentColor: "#38bdf8",
    publicAlt: "灰港静夜码头的低雾、空摊棚、巡灯和只剩少量委托牌的墙面。",
    timeOfDay: "night",
    weather: "mist",
    motif: "harbor",
  },
  {
    variantKey: "ash_outpost_sunrise",
    regionId: "region_ash_outpost",
    title: "灰烬前哨日出",
    subtitle: "训练号角、赤色晨线和炉烟巡逻",
    fileName: "ash-outpost-sunrise-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-outpost-sunrise-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-outpost-sunrise-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#17100f", "#7f1d1d", "#f97316", "#facc15"],
    accentColor: "#f97316",
    publicAlt: "灰烬前哨日出时的城墙、号角旗、炉烟和巡逻队列。",
    timeOfDay: "dawn",
    weather: "ashfall",
    motif: "outpost",
  },
  {
    variantKey: "ash_outpost_storm",
    regionId: "region_ash_outpost",
    title: "灰烬前哨火风",
    subtitle: "火星风暴、城墙哨灯和紧急集合",
    fileName: "ash-outpost-storm-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-outpost-storm-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-outpost-storm-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#120806", "#7f1d1d", "#fb923c", "#cbd5e1"],
    accentColor: "#fb923c",
    publicAlt: "灰烬前哨火风中的城墙哨灯、火星风暴和紧急集合点。",
    timeOfDay: "dusk",
    weather: "emberstorm",
    motif: "outpost",
  },
  {
    variantKey: "ash_outpost_noon_watch",
    regionId: "region_ash_outpost",
    title: "灰烬前哨正午值守",
    subtitle: "白昼炉烟、补给点名和边境瞭望",
    fileName: "ash-outpost-noon-watch-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-outpost-noon-watch-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-outpost-noon-watch-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#20100b", "#9a3412", "#fed7aa", "#facc15"],
    accentColor: "#f97316",
    publicAlt: "灰烬前哨正午值守的补给点名、城墙瞭望、炉烟和训练旗。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "outpost",
  },
  {
    variantKey: "ash_outpost_night_forge",
    regionId: "region_ash_outpost",
    title: "灰烬前哨夜炉",
    subtitle: "夜间炉光、落灰和托管者归队前的装备检修",
    fileName: "ash-outpost-night-forge-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-outpost-night-forge-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-outpost-night-forge-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#080403", "#7f1d1d", "#fb923c", "#94a3b8"],
    accentColor: "#fb923c",
    publicAlt: "灰烬前哨夜炉的落灰、装备检修台、巡灯和托管者归队前的队列。",
    timeOfDay: "night",
    weather: "ashfall",
    motif: "outpost",
  },
  {
    variantKey: "salt_mirror_noon",
    regionId: "region_salt_mirror_coast",
    title: "盐镜正午",
    subtitle: "白亮盐潮、商队阴影和公开竞价",
    fileName: "salt-mirror-noon-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-mirror-noon-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-mirror-noon-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#0f1b2c", "#0369a1", "#bae6fd", "#facc15"],
    accentColor: "#bae6fd",
    publicAlt: "盐镜正午的白亮盐潮、堤道商队、临时市棚和竞价旗。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "coast",
  },
  {
    variantKey: "salt_mirror_fog",
    regionId: "region_salt_mirror_coast",
    title: "盐镜雾汐",
    subtitle: "盐雾、低潮回声和护送灯线",
    fileName: "salt-mirror-fog-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-mirror-fog-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-mirror-fog-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#08111f", "#155e75", "#a5f3fc", "#e2e8f0"],
    accentColor: "#a5f3fc",
    publicAlt: "盐镜雾汐中的低潮盐雾、护送灯线和模糊堤道。",
    timeOfDay: "night",
    weather: "brine_fog",
    motif: "coast",
  },
  {
    variantKey: "salt_mirror_dawn_trade",
    regionId: "region_salt_mirror_coast",
    title: "盐镜晨市",
    subtitle: "晨光盐潮、早班商队和公开称量",
    fileName: "salt-mirror-dawn-trade-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-mirror-dawn-trade-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-mirror-dawn-trade-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#082032", "#0284c7", "#bae6fd", "#fde68a"],
    accentColor: "#bae6fd",
    publicAlt: "盐镜晨市的晨光盐潮、早班商队、称量台和公开竞价旗。",
    timeOfDay: "dawn",
    weather: "clear",
    motif: "coast",
  },
  {
    variantKey: "salt_mirror_twilight_brine",
    regionId: "region_salt_mirror_coast",
    title: "盐镜薄暮盐雾",
    subtitle: "薄暮返潮、盐雾灯线和护送名单",
    fileName: "salt-mirror-twilight-brine-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-mirror-twilight-brine-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-mirror-twilight-brine-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#06131f", "#155e75", "#a5f3fc", "#e2e8f0"],
    accentColor: "#a5f3fc",
    publicAlt: "盐镜薄暮盐雾中的返潮堤道、护送灯线、模糊摊棚和名单牌。",
    timeOfDay: "twilight",
    weather: "brine_fog",
    motif: "coast",
  },
  {
    variantKey: "glass_archive_morning",
    regionId: "region_glass_archive",
    title: "玻璃档案晨检",
    subtitle: "透明书塔、索引晨光和公开誓言复核",
    fileName: "glass-archive-morning-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/glass-archive-morning-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/glass-archive-morning-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#0f1720", "#0f766e", "#a7f3d0", "#f8fafc"],
    accentColor: "#a7f3d0",
    publicAlt: "玻璃档案晨检时的透明书塔、索引晨光和公开誓言阶梯。",
    timeOfDay: "morning",
    weather: "clear",
    motif: "archive",
  },
  {
    variantKey: "glass_archive_eclipse",
    regionId: "region_glass_archive",
    title: "玻璃档案蚀影",
    subtitle: "暗蚀索引、静默桥和封存回声",
    fileName: "glass-archive-eclipse-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/glass-archive-eclipse-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/glass-archive-eclipse-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#050816", "#164e63", "#67e8f9", "#c4b5fd"],
    accentColor: "#67e8f9",
    publicAlt: "玻璃档案蚀影下的暗色索引桥、封存回声和冷光书塔。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "archive",
  },
  {
    variantKey: "glass_archive_noon_index",
    regionId: "region_glass_archive",
    title: "玻璃档案正午索引",
    subtitle: "正午检索光、索引桥和公开誓言校验",
    fileName: "glass-archive-noon-index-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/glass-archive-noon-index-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/glass-archive-noon-index-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#07131a", "#0f766e", "#ccfbf1", "#f8fafc"],
    accentColor: "#99f6e4",
    publicAlt: "玻璃档案正午索引时的检索光、索引桥、透明书塔和公开誓言校验席。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "archive",
  },
  {
    variantKey: "glass_archive_twilight_vigil",
    regionId: "region_glass_archive",
    title: "玻璃档案薄暮守夜",
    subtitle: "薄暮静桥、雾化索引和夜班封存",
    fileName: "glass-archive-twilight-vigil-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/glass-archive-twilight-vigil-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/glass-archive-twilight-vigil-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#06111a", "#164e63", "#67e8f9", "#c4b5fd"],
    accentColor: "#67e8f9",
    publicAlt: "玻璃档案薄暮守夜的静桥、雾化索引、封存灯和冷光书塔。",
    timeOfDay: "twilight",
    weather: "mist",
    motif: "archive",
  },
  {
    variantKey: "moonwell_hollow_twilight",
    regionId: "region_moonwell_hollow",
    title: "月井空壳薄暮",
    subtitle: "银井薄暮、苔光台阶和托管修炼席",
    fileName: "moonwell-hollow-twilight-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/moonwell-hollow-twilight-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/moonwell-hollow-twilight-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#0b1020", "#581c87", "#c4b5fd", "#22c55e"],
    accentColor: "#c4b5fd",
    publicAlt: "月井空壳薄暮中的银井、苔光台阶、托管修炼席和低语树影。",
    timeOfDay: "twilight",
    weather: "silver_dust",
    motif: "moonwell",
  },
  {
    variantKey: "moonwell_hollow_night",
    regionId: "region_moonwell_hollow",
    title: "月井空壳月夜",
    subtitle: "月井倒影、低语树冠和静默结界",
    fileName: "moonwell-hollow-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/moonwell-hollow-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/moonwell-hollow-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#07071a", "#312e81", "#a5b4fc", "#22c55e"],
    accentColor: "#a5b4fc",
    publicAlt: "月井空壳月夜的月井倒影、低语树冠、静默结界和修炼席。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "moonwell",
  },
  {
    variantKey: "moonwell_hollow_dawn_training",
    regionId: "region_moonwell_hollow",
    title: "月井空壳晨修",
    subtitle: "晨间银尘、苔光台阶和静默体术",
    fileName: "moonwell-hollow-dawn-training-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/moonwell-hollow-dawn-training-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/moonwell-hollow-dawn-training-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#08111f", "#4c1d95", "#c4b5fd", "#86efac"],
    accentColor: "#c4b5fd",
    publicAlt: "月井空壳晨修的银尘、苔光台阶、静默体术席和低语树影。",
    timeOfDay: "dawn",
    weather: "silver_dust",
    motif: "moonwell",
  },
  {
    variantKey: "moonwell_hollow_noon_grove",
    regionId: "region_moonwell_hollow",
    title: "月井空壳正午林地",
    subtitle: "正午苔光、亲友祈愿牌和托管休整席",
    fileName: "moonwell-hollow-noon-grove-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/moonwell-hollow-noon-grove-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/moonwell-hollow-noon-grove-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#0b1720", "#166534", "#86efac", "#c4b5fd"],
    accentColor: "#86efac",
    publicAlt: "月井空壳正午林地的苔光、亲友祈愿牌、托管休整席和银井倒影。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "moonwell",
  },
  {
    variantKey: "black_harbor_fog_dawn",
    regionId: "region_blackharbor",
    title: "黑港雾晨",
    subtitle: "潮雾、蓝色信号灯和早班税棚开封",
    fileName: "black-harbor-fog-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/black-harbor-fog-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/black-harbor-fog-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#04070b", "#172554", "#38bdf8", "#fbbf24"],
    accentColor: "#38bdf8",
    publicAlt: "黑港雾晨的潮雾、蓝色信号灯、早班税棚和封蜡账册。",
    timeOfDay: "dawn",
    weather: "brine_fog",
    motif: "blackharbor",
  },
  {
    variantKey: "black_harbor_low_tide_night",
    regionId: "region_blackharbor",
    title: "黑港低潮夜",
    subtitle: "低潮船影、暗色屋顶和公开榜单前的守夜人",
    fileName: "black-harbor-low-tide-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/black-harbor-low-tide-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/black-harbor-low-tide-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#0f172a", "#60a5fa", "#d97706"],
    accentColor: "#60a5fa",
    publicAlt: "黑港低潮夜的船影、暗色屋顶、低蓝巡灯和公开榜单前的守夜人。",
    timeOfDay: "night",
    weather: "mist",
    motif: "blackharbor",
  },
  {
    variantKey: "forest_green_dawn",
    regionId: "region_forest",
    title: "誓林绿晨",
    subtitle: "晨光树冠、湿叶小径和刚挂起的猎人誓牌",
    fileName: "forest-green-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/forest-green-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/forest-green-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#06110a", "#14532d", "#86efac", "#fde68a"],
    accentColor: "#86efac",
    publicAlt: "誓林绿晨的树冠晨光、湿叶小径、猎人誓牌和深林委托灯。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "forest",
  },
  {
    variantKey: "forest_rain_glade",
    regionId: "region_forest",
    title: "誓林雨中空地",
    subtitle: "雨线、苔光小祠和等待疗养的亲友祈牌",
    fileName: "forest-rain-glade-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/forest-rain-glade-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/forest-rain-glade-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#03100a", "#166534", "#bbf7d0", "#94a3b8"],
    accentColor: "#bbf7d0",
    publicAlt: "誓林雨中空地的雨线、苔光小祠、亲友祈牌和等待疗养的席位。",
    timeOfDay: "dusk",
    weather: "rain",
    motif: "forest",
  },
  {
    variantKey: "salt_gate_wind_dawn",
    regionId: "region_salt_gate",
    title: "盐门风晨",
    subtitle: "晨盐风、关税旗和刚开启的通行审查",
    fileName: "salt-gate-wind-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-gate-wind-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-gate-wind-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#06131f", "#155e75", "#e0f2fe", "#fbbf24"],
    accentColor: "#bae6fd",
    publicAlt: "盐门风晨的盐雾、关税旗、晨间通行审查和边境车队灯线。",
    timeOfDay: "dawn",
    weather: "brine_fog",
    motif: "saltgate",
  },
  {
    variantKey: "salt_gate_market_noon",
    regionId: "region_salt_gate",
    title: "盐门正午市桥",
    subtitle: "正午盐光、桥上市集和公开称量的货单",
    fileName: "salt-gate-market-noon-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/salt-gate-market-noon-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/salt-gate-market-noon-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#081827", "#0e7490", "#cffafe", "#f59e0b"],
    accentColor: "#f59e0b",
    publicAlt: "盐门正午市桥的盐光、桥上摊棚、公开称量货单和巡税旗线。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "saltgate",
  },
  {
    variantKey: "ash_waste_red_dusk",
    regionId: "region_ash",
    title: "灰烬荒道赤暮",
    subtitle: "赤色薄暮、火星风和赶在夜前入营的护送车队",
    fileName: "ash-waste-red-dusk-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-waste-red-dusk-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-waste-red-dusk-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#140806", "#7c2d12", "#fb923c", "#facc15"],
    accentColor: "#fb923c",
    publicAlt: "灰烬荒道赤暮的火星风、车辙灯、补给旗和赶在夜前入营的护送队。",
    timeOfDay: "dusk",
    weather: "emberstorm",
    motif: "ashwaste",
  },
  {
    variantKey: "ash_waste_cold_night",
    regionId: "region_ash",
    title: "灰烬荒原冷夜",
    subtitle: "冷灰夜、渣井余光和荒道营地的低声点名",
    fileName: "ash-waste-cold-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/ash-waste-cold-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/ash-waste-cold-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#050506", "#7f1d1d", "#f97316", "#94a3b8"],
    accentColor: "#f97316",
    publicAlt: "灰烬荒原冷夜的落灰、渣井余光、营地低声点名和远处黑铁吊架。",
    timeOfDay: "night",
    weather: "ashfall",
    motif: "ashwaste",
  },
  {
    variantKey: "city_pipes_sodium_dawn",
    regionId: "region_city_pipes",
    title: "城市管道钠灯晨雾",
    subtitle: "晨雾、钠灯和刚开张的阀门市集",
    fileName: "city-pipes-sodium-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/city-pipes-sodium-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/city-pipes-sodium-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020605", "#14532d", "#5eead4", "#facc15"],
    accentColor: "#5eead4",
    publicAlt: "城市管道钠灯晨雾中的阀门市集、冷凝水渠、检修桥和临时委托灯。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "citypipes",
  },
  {
    variantKey: "city_pipes_overflow_night",
    regionId: "region_city_pipes",
    title: "城市管道溢流夜",
    subtitle: "夜间溢流、检修红灯和回声爬廊",
    fileName: "city-pipes-overflow-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/city-pipes-overflow-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/city-pipes-overflow-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#010403", "#0f3f2f", "#2dd4bf", "#f87171"],
    accentColor: "#2dd4bf",
    publicAlt: "城市管道溢流夜的回声爬廊、检修红灯、潮湿阀门和低处水线。",
    timeOfDay: "night",
    weather: "rain",
    motif: "citypipes",
  },
  {
    variantKey: "abandoned_mine_dust_noon",
    regionId: "region_abandoned_mine",
    title: "废弃矿区尘午",
    subtitle: "正午尘光、塌方轨道和旧升降塔阴影",
    fileName: "abandoned-mine-dust-noon-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/abandoned-mine-dust-noon-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/abandoned-mine-dust-noon-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#0b0806", "#57534e", "#f59e0b", "#cbd5e1"],
    accentColor: "#f59e0b",
    publicAlt: "废弃矿区尘午的旧升降塔、塌方轨道、矿车影和封存警戒线。",
    timeOfDay: "noon",
    weather: "ashfall",
    motif: "mine",
  },
  {
    variantKey: "abandoned_mine_blue_night",
    regionId: "region_abandoned_mine",
    title: "废弃矿区蓝尘夜",
    subtitle: "蓝尘矿灯、深井回声和夜间封锁线",
    fileName: "abandoned-mine-blue-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/abandoned-mine-blue-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/abandoned-mine-blue-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#070605", "#44403c", "#60a5fa", "#f59e0b"],
    accentColor: "#60a5fa",
    publicAlt: "废弃矿区蓝尘夜的深井回声、蓝色矿灯、残旧轨道和夜间封锁线。",
    timeOfDay: "night",
    weather: "silver_dust",
    motif: "mine",
  },
  {
    variantKey: "data_tower_static_dawn",
    regionId: "region_data_tower",
    title: "废弃数据塔静电黎明",
    subtitle: "黎明静电、缓存雾和脑晶索引灯",
    fileName: "data-tower-static-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/data-tower-static-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/data-tower-static-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#030712", "#1e1b4b", "#67e8f9", "#c4b5fd"],
    accentColor: "#67e8f9",
    publicAlt: "废弃数据塔静电黎明的缓存雾、脑晶索引灯、断裂塔脊和维护桥。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "data-tower",
  },
  {
    variantKey: "data_tower_cache_rain",
    regionId: "region_data_tower",
    title: "废弃数据塔缓存雨",
    subtitle: "夜间缓存雨、索引桥和闪烁服务器封条",
    fileName: "data-tower-cache-rain-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/data-tower-cache-rain-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/data-tower-cache-rain-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#312e81", "#22d3ee", "#a78bfa"],
    accentColor: "#22d3ee",
    publicAlt: "废弃数据塔缓存雨夜的索引桥、服务器封条、蓝色数据雨和脑晶灯列。",
    timeOfDay: "night",
    weather: "rain",
    motif: "data-tower",
  },
  {
    variantKey: "orbit_city_sunrise_dock",
    regionId: "region_orbit_city",
    title: "轨道城日出泊港",
    subtitle: "日出低轨、环站泊位和星历灯市开市",
    fileName: "orbit-city-sunrise-dock-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/orbit-city-sunrise-dock-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/orbit-city-sunrise-dock-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#0f172a", "#93c5fd", "#fde68a"],
    accentColor: "#93c5fd",
    publicAlt: "轨道城日出泊港的低轨晨线、环站泊位、悬浮摊位和星历交通灯。",
    timeOfDay: "dawn",
    weather: "clear",
    motif: "orbit-city",
  },
  {
    variantKey: "orbit_city_eclipse_watch",
    regionId: "region_orbit_city",
    title: "轨道城蚀影守望",
    subtitle: "轨道蚀影、信标塔和夜间审判航道",
    fileName: "orbit-city-eclipse-watch-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/orbit-city-eclipse-watch-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/orbit-city-eclipse-watch-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#01040d", "#1e1b4b", "#bfdbfe", "#facc15"],
    accentColor: "#bfdbfe",
    publicAlt: "轨道城蚀影守望的信标塔、夜间审判航道、环形站台和冷白星光。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "orbit-city",
  },
  {
    variantKey: "trench_blue_midnight",
    regionId: "region_trench",
    title: "海沟蓝午夜",
    subtitle: "冷蓝水压、守梦灯标和静默下潜",
    fileName: "trench-blue-midnight-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/trench-blue-midnight-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/trench-blue-midnight-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#010814", "#0f3f46", "#67e8f9", "#a7f3d0"],
    accentColor: "#67e8f9",
    publicAlt: "海沟蓝午夜的冷蓝水压、守梦灯标、深海岩架和静默下潜绳桥。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "trench",
  },
  {
    variantKey: "trench_pressure_fog",
    regionId: "region_trench",
    title: "海沟水压雾晨",
    subtitle: "晨雾水压、古梦暗流和折寿风险灯",
    fileName: "trench-pressure-fog-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/trench-pressure-fog-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/trench-pressure-fog-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#134e4a", "#5eead4", "#cbd5e1"],
    accentColor: "#5eead4",
    publicAlt: "海沟水压雾晨的古梦暗流、冷凝雾带、折寿风险灯和远处浮游光。",
    timeOfDay: "dawn",
    weather: "brine_fog",
    motif: "trench",
  },
  {
    variantKey: "collective_dream_pool_twilight",
    regionId: "region_collective_dream_pool",
    title: "集体梦池薄暮",
    subtitle: "薄暮梦面、记忆浮岛和共享睡眠灯列",
    fileName: "collective-dream-pool-twilight-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/collective-dream-pool-twilight-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/collective-dream-pool-twilight-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#090513", "#4c1d95", "#c084fc", "#22d3ee"],
    accentColor: "#c084fc",
    publicAlt: "集体梦池薄暮的共享梦面、记忆浮岛、身份倒影和梦灯列。",
    timeOfDay: "twilight",
    weather: "silver_dust",
    motif: "dream-pool",
  },
  {
    variantKey: "collective_dream_pool_eclipse",
    regionId: "region_collective_dream_pool",
    title: "集体梦池蚀影",
    subtitle: "蚀影梦面、服务器封条和传说倒影",
    fileName: "collective-dream-pool-eclipse-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/collective-dream-pool-eclipse-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/collective-dream-pool-eclipse-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#05020d", "#312e81", "#a78bfa", "#67e8f9"],
    accentColor: "#a78bfa",
    publicAlt: "集体梦池蚀影中的服务器封条、传说倒影、暗色梦面和记忆浮岛。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "dream-pool",
  },
  {
    variantKey: "space_rift_violet_dawn",
    regionId: "region_space_rift",
    title: "空间裂缝紫黎明",
    subtitle: "紫色裂光、晨间落尘和临时通行刻度",
    fileName: "space-rift-violet-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/space-rift-violet-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/space-rift-violet-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#07021a", "#312e81", "#c084fc", "#67e8f9"],
    accentColor: "#c084fc",
    publicAlt: "空间裂缝紫黎明的裂光、晨间落尘、通行刻度和错位门框。",
    timeOfDay: "dawn",
    weather: "silver_dust",
    motif: "space-rift",
  },
  {
    variantKey: "space_rift_starfall_night",
    regionId: "region_space_rift",
    title: "空间裂缝星坠夜",
    subtitle: "星屑雨、错位边缘和跨维桥影",
    fileName: "space-rift-starfall-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/space-rift-starfall-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/space-rift-starfall-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#05020d", "#1e1b4b", "#a78bfa", "#bfdbfe"],
    accentColor: "#a78bfa",
    publicAlt: "空间裂缝星坠夜的星屑雨、跨维桥影、错位边缘和远处裂光。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "space-rift",
  },
  {
    variantKey: "non_euclidean_cave_bent_noon",
    regionId: "region_non_euclidean_cave",
    title: "非欧洞窟折角正午",
    subtitle: "正午测量灯、折叠阶梯和重力错位",
    fileName: "non-euclidean-cave-bent-noon-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/non-euclidean-cave-bent-noon-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/non-euclidean-cave-bent-noon-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#080414", "#3b0764", "#c4b5fd", "#facc15"],
    accentColor: "#c4b5fd",
    publicAlt: "非欧洞窟折角正午的测量灯、错误楼梯、折叠岩壁和重力错位线。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "non-euclidean",
  },
  {
    variantKey: "non_euclidean_cave_eclipse_fold",
    regionId: "region_non_euclidean_cave",
    title: "非欧洞窟蚀影折页",
    subtitle: "蚀影回声、倒置路径和无法闭合的门",
    fileName: "non-euclidean-cave-eclipse-fold-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/non-euclidean-cave-eclipse-fold-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/non-euclidean-cave-eclipse-fold-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#03010a", "#2e1065", "#a78bfa", "#fde68a"],
    accentColor: "#a78bfa",
    publicAlt: "非欧洞窟蚀影折页里的倒置路径、错误门框、黄铜灯和紫色重力回声。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "non-euclidean",
  },
  {
    variantKey: "starship_graveyard_cold_dawn",
    regionId: "region_starship_graveyard",
    title: "星舰墓场冷白黎明",
    subtitle: "冷轨残骸、银尘晨线和漂航信标",
    fileName: "starship-graveyard-cold-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/starship-graveyard-cold-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/starship-graveyard-cold-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#172554", "#93c5fd", "#facc15"],
    accentColor: "#93c5fd",
    publicAlt: "星舰墓场冷白黎明中的银尘晨线、断裂船壳、漂航信标和打捞禁线。",
    timeOfDay: "dawn",
    weather: "silver_dust",
    motif: "starship-graveyard",
  },
  {
    variantKey: "starship_graveyard_eclipse_drift",
    regionId: "region_starship_graveyard",
    title: "星舰墓场蚀影漂航",
    subtitle: "蚀影残骸、冷白信标和碎星静默",
    fileName: "starship-graveyard-eclipse-drift-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/starship-graveyard-eclipse-drift-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/starship-graveyard-eclipse-drift-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#01040c", "#1e1b4b", "#bfdbfe", "#fde68a"],
    accentColor: "#bfdbfe",
    publicAlt: "星舰墓场蚀影漂航里的暗化船壳、冷白信标、牵引线和碎星静默。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "starship-graveyard",
  },
  {
    variantKey: "abandoned_subway_mist_morning",
    regionId: "region_abandoned_subway",
    title: "废弃地铁雾晨",
    subtitle: "潮湿晨雾、旧信号灯和空站台",
    fileName: "abandoned-subway-mist-morning-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/abandoned-subway-mist-morning-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/abandoned-subway-mist-morning-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#050807", "#1f2937", "#5eead4", "#f59e0b"],
    accentColor: "#5eead4",
    publicAlt: "废弃地铁雾晨中的潮湿站台、旧信号灯、锈蚀闸机和空轨道。",
    timeOfDay: "morning",
    weather: "mist",
    motif: "abandoned-subway",
  },
  {
    variantKey: "abandoned_subway_moonlit_tunnel",
    regionId: "region_abandoned_subway",
    title: "废弃地铁月照隧道",
    subtitle: "月光渗入、积水倒影和远处青灯",
    fileName: "abandoned-subway-moonlit-tunnel-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/abandoned-subway-moonlit-tunnel-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/abandoned-subway-moonlit-tunnel-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020503", "#111827", "#67e8f9", "#d1d5db"],
    accentColor: "#67e8f9",
    publicAlt: "废弃地铁月照隧道的积水倒影、远处青灯、半开闸机和旧轨道。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "abandoned-subway",
  },
  {
    variantKey: "holographic_theater_neon_dusk",
    regionId: "region_holographic_theater",
    title: "全息剧场霓虹薄暮",
    subtitle: "薄暮光幕、伪掌声预热和空座席反光",
    fileName: "holographic-theater-neon-dusk-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/holographic-theater-neon-dusk-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/holographic-theater-neon-dusk-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#050816", "#4c1d95", "#f472b6", "#67e8f9"],
    accentColor: "#f472b6",
    publicAlt: "全息剧场霓虹薄暮里的光谱舞台、伪掌声预热灯和空座席反光。",
    timeOfDay: "dusk",
    weather: "clear",
    motif: "holographic-theater",
  },
  {
    variantKey: "holographic_theater_rain_rehearsal",
    regionId: "region_holographic_theater",
    title: "全息剧场雨中彩排",
    subtitle: "雨线投影、折光后台和循环台词",
    fileName: "holographic-theater-rain-rehearsal-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/holographic-theater-rain-rehearsal-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/holographic-theater-rain-rehearsal-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#701a75", "#f0abfc", "#a5f3fc"],
    accentColor: "#f0abfc",
    publicAlt: "全息剧场雨中彩排的雨线投影、折光后台、循环台词光幕和伪掌声席。",
    timeOfDay: "night",
    weather: "rain",
    motif: "holographic-theater",
  },
  {
    variantKey: "quantum_laboratory_probability_morning",
    regionId: "region_quantum_laboratory",
    title: "量子实验室概率晨检",
    subtitle: "晨间银尘、概率玻璃和同步观测环",
    fileName: "quantum-laboratory-probability-morning-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/quantum-laboratory-probability-morning-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/quantum-laboratory-probability-morning-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#164e63", "#67e8f9", "#facc15"],
    accentColor: "#67e8f9",
    publicAlt: "量子实验室概率晨检中的银尘、概率玻璃、同步观测环和金色警戒灯。",
    timeOfDay: "morning",
    weather: "silver_dust",
    motif: "quantum-laboratory",
  },
  {
    variantKey: "quantum_laboratory_eclipse_trial",
    regionId: "region_quantum_laboratory",
    title: "量子实验室蚀影试验",
    subtitle: "蚀影观测、坍缩桥和锁定实验门",
    fileName: "quantum-laboratory-eclipse-trial-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/quantum-laboratory-eclipse-trial-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/quantum-laboratory-eclipse-trial-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#01040c", "#0f766e", "#99f6e4", "#fde68a"],
    accentColor: "#99f6e4",
    publicAlt: "量子实验室蚀影试验里的坍缩桥、概率线、锁定实验门和暗化观测窗。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "quantum-laboratory",
  },
  {
    variantKey: "reflective_city_glare_noon",
    regionId: "region_reflective_city",
    title: "反光城市眩光正午",
    subtitle: "正午镜面、白亮楼幕和公开巡游线",
    fileName: "reflective-city-glare-noon-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/reflective-city-glare-noon-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/reflective-city-glare-noon-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#061018", "#0f766e", "#a5f3fc", "#f472b6"],
    accentColor: "#a5f3fc",
    publicAlt: "反光城市眩光正午的白亮镜面楼幕、屏幕水岸、公开巡游线和霓虹残影。",
    timeOfDay: "noon",
    weather: "clear",
    motif: "reflective-city",
  },
  {
    variantKey: "reflective_city_neon_rain",
    regionId: "region_reflective_city",
    title: "反光城市霓虹雨夜",
    subtitle: "雨中镜街、屏幕倒影和粉青灯幕",
    fileName: "reflective-city-neon-rain-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/reflective-city-neon-rain-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/reflective-city-neon-rain-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#0f766e", "#67e8f9", "#f472b6"],
    accentColor: "#f472b6",
    publicAlt: "反光城市霓虹雨夜的雨线、镜面街道、屏幕倒影和粉青公开路牌。",
    timeOfDay: "night",
    weather: "rain",
    motif: "reflective-city",
  },
  {
    variantKey: "data_alley_static_dawn",
    regionId: "region_data_alley",
    title: "数据巷静电黎明",
    subtitle: "晨间静电、缓存招牌和线缆天幕",
    fileName: "data-alley-static-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/data-alley-static-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/data-alley-static-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#030712", "#1e1b4b", "#67e8f9", "#f59e0b"],
    accentColor: "#67e8f9",
    publicAlt: "数据巷静电黎明里的缓存招牌、晨雾走线、线缆天幕和临时认证灯。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "data-alley",
  },
  {
    variantKey: "data_alley_blackout_night",
    regionId: "region_data_alley",
    title: "数据巷断电月夜",
    subtitle: "月照黑巷、备用灯箱和包市场静默",
    fileName: "data-alley-blackout-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/data-alley-blackout-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/data-alley-blackout-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#1e1b4b", "#67e8f9", "#fbbf24"],
    accentColor: "#67e8f9",
    publicAlt: "数据巷断电月夜中的备用灯箱、静默包市场、月照走线和服务器结算牌。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "data-alley",
  },
  {
    variantKey: "prism_waters_rainbow_dawn",
    regionId: "region_prism_waters",
    title: "棱镜水域彩潮黎明",
    subtitle: "晨雾折光、彩带潮线和镜帆启航",
    fileName: "prism-waters-rainbow-dawn-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/prism-waters-rainbow-dawn-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/prism-waters-rainbow-dawn-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#03111f", "#155e75", "#a7f3d0", "#f0abfc"],
    accentColor: "#a7f3d0",
    publicAlt: "棱镜水域彩潮黎明中的晨雾折光、彩带潮线、镜帆启航和服务器航标。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "prism-waters",
  },
  {
    variantKey: "prism_waters_fog_night",
    regionId: "region_prism_waters",
    title: "棱镜水域雾夜",
    subtitle: "夜雾透镜、青紫水标和低声镜帆",
    fileName: "prism-waters-fog-night-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/prism-waters-fog-night-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/prism-waters-fog-night-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#164e63", "#67e8f9", "#e879f9"],
    accentColor: "#67e8f9",
    publicAlt: "棱镜水域雾夜里的透镜码头、青紫水标、低声镜帆和月下折光潮。",
    timeOfDay: "night",
    weather: "brine_fog",
    motif: "prism-waters",
  },
  {
    variantKey: "probability_greenhouse_morning_bloom",
    regionId: "region_probability_greenhouse",
    title: "概率温室晨间开花",
    subtitle: "晨光玻璃、分支花床和可能性种子",
    fileName: "probability-greenhouse-morning-bloom-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/probability-greenhouse-morning-bloom-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/probability-greenhouse-morning-bloom-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#04130a", "#166534", "#bef264", "#facc15"],
    accentColor: "#bef264",
    publicAlt: "概率温室晨间开花时的玻璃棚、分支花床、可能性种子和服务器观测灯。",
    timeOfDay: "morning",
    weather: "clear",
    motif: "probability-greenhouse",
  },
  {
    variantKey: "probability_greenhouse_eclipse_harvest",
    regionId: "region_probability_greenhouse",
    title: "概率温室蚀影收获",
    subtitle: "蚀影玻璃、坍缩收获格和金色种子价签",
    fileName: "probability-greenhouse-eclipse-harvest-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/probability-greenhouse-eclipse-harvest-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/probability-greenhouse-eclipse-harvest-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#021308", "#14532d", "#a3e635", "#fde68a"],
    accentColor: "#a3e635",
    publicAlt: "概率温室蚀影收获中的暗化玻璃、坍缩收获格、金色种子价签和服务器倒计时。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "probability-greenhouse",
  },
  {
    variantKey: "prophecy_server_dawn_query",
    regionId: "region_prophecy_server",
    title: "预言服务器晨间询问",
    subtitle: "冷启动机柜、蓝白查询光和神谕缓存队列",
    fileName: "prophecy-server-dawn-query-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/prophecy-server-dawn-query-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/prophecy-server-dawn-query-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#020617", "#1e1b4b", "#93c5fd", "#facc15"],
    accentColor: "#93c5fd",
    publicAlt: "预言服务器晨间询问时的冷启动机柜、蓝白查询光、神谕缓存队列和判定环。",
    timeOfDay: "dawn",
    weather: "mist",
    motif: "prophecy-server",
  },
  {
    variantKey: "prophecy_server_eclipse_verdict",
    regionId: "region_prophecy_server",
    title: "预言服务器蚀影判定",
    subtitle: "黑屏判定厅、金色裁决线和延迟上诉队列",
    fileName: "prophecy-server-eclipse-verdict-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/prophecy-server-eclipse-verdict-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/prophecy-server-eclipse-verdict-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#02030a", "#111827", "#60a5fa", "#fbbf24"],
    accentColor: "#60a5fa",
    publicAlt: "预言服务器蚀影判定中的黑屏判定厅、金色裁决线、延迟上诉队列和低温服务器列阵。",
    timeOfDay: "night",
    weather: "eclipse",
    motif: "prophecy-server",
  },
  {
    variantKey: "orbital_cathedral_sunrise_bells",
    regionId: "region_orbital_cathedral",
    title: "轨道教堂日升鸣钟",
    subtitle: "低轨晨光、钟环阴影和舷窗圣歌",
    fileName: "orbital-cathedral-sunrise-bells-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/orbital-cathedral-sunrise-bells-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/orbital-cathedral-sunrise-bells-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#07030f", "#312e81", "#f8fafc", "#f59e0b"],
    accentColor: "#f8fafc",
    publicAlt: "轨道教堂日升鸣钟时的低轨晨光、钟环阴影、舷窗圣歌和白金中殿。",
    timeOfDay: "dawn",
    weather: "clear",
    motif: "orbital-cathedral",
  },
  {
    variantKey: "orbital_cathedral_moonlit_procession",
    regionId: "region_orbital_cathedral",
    title: "轨道教堂月下行列",
    subtitle: "月照中殿、环形队列和无声告解舱",
    fileName: "orbital-cathedral-moonlit-procession-scene-variant.png",
    path: "obsidian-epoch/assets/scene-variant/orbital-cathedral-moonlit-procession-scene-variant.png",
    url: "/api/epoch/assets/scene-variant/orbital-cathedral-moonlit-procession-scene-variant.png",
    contentType: EPOCH_SCENE_VARIANT_CONTENT_TYPE,
    width: EPOCH_SCENE_VARIANT_WIDTH,
    height: EPOCH_SCENE_VARIANT_HEIGHT,
    palette: ["#050716", "#1e1b4b", "#c4b5fd", "#f8fafc"],
    accentColor: "#c4b5fd",
    publicAlt: "轨道教堂月下行列中的月照中殿、环形队列、无声告解舱和低轨窗光。",
    timeOfDay: "night",
    weather: "moonlit",
    motif: "orbital-cathedral",
  },
] as const satisfies readonly EpochSceneVariantRecord[];

function sceneVariantFilePath(asset: EpochSceneVariantRecord, packageRoot = defaultPackageRoot) {
  return join(packageRoot, asset.path);
}

export function epochSceneVariantByFileName(fileName: string): EpochSceneVariantRecord | undefined {
  return EPOCH_SCENE_VARIANTS.find((asset) => asset.fileName === fileName);
}

export function epochSceneVariantsForRegion(regionId: string): readonly EpochSceneVariantRecord[] {
  const mediaRegionId = resolveEpochMediaRegionId(regionId);
  return EPOCH_SCENE_VARIANTS.filter((asset) => asset.regionId === mediaRegionId);
}

export async function readEpochSceneVariantByFileName(fileName: string, packageRoot = defaultPackageRoot) {
  const asset = epochSceneVariantByFileName(fileName);
  if (!asset) return undefined;
  const content = await readFile(sceneVariantFilePath(asset, packageRoot));
  return { asset, content };
}

export async function epochSceneVariantManifestEntries(packageRoot = defaultPackageRoot): Promise<EpochSceneVariantManifestEntry[]> {
  return Promise.all(EPOCH_SCENE_VARIANTS.map(async (asset) => {
    const content = await readFile(sceneVariantFilePath(asset, packageRoot));
    return {
      variantKey: asset.variantKey,
      regionId: asset.regionId,
      title: asset.title,
      subtitle: asset.subtitle,
      path: asset.path,
      url: asset.url,
      contentType: asset.contentType,
      width: asset.width,
      height: asset.height,
      timeOfDay: asset.timeOfDay,
      weather: asset.weather,
      sha256: createHash("sha256").update(content).digest("hex"),
    };
  }));
}

export function epochSceneVariantMedia(asset: EpochSceneVariantRecord): EpochSceneVariantMedia {
  return {
    variantKey: asset.variantKey,
    regionId: asset.regionId,
    title: asset.title,
    subtitle: asset.subtitle,
    palette: asset.palette,
    accentColor: asset.accentColor,
    publicAlt: asset.publicAlt,
    assetPath: asset.path,
    imageUrl: asset.url,
    contentType: asset.contentType,
    width: asset.width,
    height: asset.height,
    timeOfDay: asset.timeOfDay,
    weather: asset.weather,
  };
}
